# Generated by Django 4.1.3 on 2023-04-14 19:07

import app.app_shop.utils.models.saving_files
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время добавления товара"
                    ),
                ),
                ("characteristics", models.JSONField(verbose_name="Характеристики")),
                ("price", models.FloatField()),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(90)],
                        verbose_name="Скидка (в %)",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Кол-во"),
                ),
                (
                    "limited_edition",
                    models.BooleanField(
                        default=False, verbose_name="Ограниченный тираж"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_shop.categoryproduct",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Теги для товаров"),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        choices=[(True, "Удалено"), (False, "Активно")],
                        default=False,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег для товара",
                "verbose_name_plural": "Теги для товаров",
                "db_table": "product_tags",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="Название изображения"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=app.app_shop.utils.models.saving_files.saving_images_for_product,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_shop.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "db_table": "product_images",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                to="app_shop.producttags", verbose_name="Теги"
            ),
        ),
    ]
