# Generated by Django 4.1.3 on 2023-04-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_product_producttags_productimages_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='definition',
        ),
    ]
