# Generated by Django 4.1.3 on 2023-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_producttags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='URL'),
        ),
    ]
