# Generated by Django 4.1.3 on 2023-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_alter_producttags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, verbose_name='URL'),
        ),
    ]
