# Generated by Django 4.1.3 on 2023-05-14 18:27

import app_shop.utils.models.saving_files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.ImageField(upload_to=app_shop.utils.models.saving_files.saving_the_category_image, verbose_name='Изображение'),
        ),
    ]
