# Generated by Django 4.1.3 on 2023-05-27 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0015_remove_cart_buyer_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
