# Generated by Django 4.1.3 on 2023-06-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0023_productbrowsinghistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productbrowsinghistory",
            options={"ordering": ["-viewing_time"]},
        ),
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app_shop.product",
                verbose_name="Товар",
            ),
        ),
    ]
