# Generated by Django 4.1.3 on 2023-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_profile_full_name_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Удалено'), (False, 'Активно')], default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Удалено'), (False, 'Активно')], default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='seller',
            name='deleted',
            field=models.BooleanField(choices=[(True, 'Удалено'), (False, 'Активно')], default=False, verbose_name='Статус'),
        ),
    ]
